obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT224)	+= atmel_mxt224.o
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT_FORK) += atmel_mxt_ts.o
obj-$(CONFIG_TOUCHSCREEN_R69001_I2C)	+= r69001-ts-i2c.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI4_FORK) += rmi4/
obj-$(CONFIG_TOUCHSCREEN_GOODIX_GT9XX) += gt9xx/
obj-$(CONFIG_TOUCHSCREEN_IT7260) += it7260_ts_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FTXXXX) += ftxxxx.o 
ftxxxx-objs += ftxxxx_ts.o ftxxxx_ex_fun.o focaltech_ctl.o test_lib.o ini.o
