obj-$(CONFIG_CHARGER_BQ24192)	+= bq24192_charger.o
obj-$(CONFIG_BQ24261_CHARGER)	+= bq24261_charger.o
obj-$(CONFIG_BQ51003_POWER)	+= bq51003_power.o
obj-$(CONFIG_BQ24232_CHARGER)	+= bq24232_charger.o
obj-$(CONFIG_PMIC_CCSM) += pmic_ccsm.o
